# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Beijing on Rails
email: beijingonrails@ecuachina.com
description: >
  It is a Meetup Community for anyone interested on Ruby on Rails in nice learning, fun coding, and happy with us.
  Feel free join into our group.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beijingonrails.org"
twitter_username: beijingonrails
github_username:  beijingonrails
timezone: Asia/Shanghai

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /:categories/:title.html
